### PR TITLE
Add very simple alpha warning

### PR DESCRIPTION
**Pull request by TheLastProject**
Tox hasn't been audited yet and still contains bugs. A small warning would help to protect our reputation in case of disaster. This can be removed when we reach final, but is good to keep for the time being, so people don't assume Tox will work perfectly.

### CODE REVIEW

**Comment by pwnsdx** [comment]
Why not, what do you think @stqism ?

**Comment by stqism** [comment]
@pwnsdx I'd rather fork that fork me on github css banner and replace it word alpha, shoved on the top right.

Worst comes to worst, add the word nightly to the button and shove a little bug icon on top.

**Comment by urras** [comment]
@stqism Why not both?

**Comment by stqism** [comment]
@urras People don't really read warnings, but something like
screen shot 2015-04-04 at 9 05 07 pm
would be really effective at proving the point without potentially scaring those who do read.

**Comment by stal888** [comment]
How much does it cost?

**Comment by stqism** [comment]
Personally, @pwnsdx, I think that the bug icon/word alpha and a getting started one time screen sorta like 
screen shot 2015-04-04 at 9 25 55 pm
would end up being far more helpful in all aspects. Personally, I don't see a point in warning people it's going to potentially be broken or buggy if we people don't know of a way to submit feedback and bugs to actually fix the issues.

**Comment by stqism** [comment]
@stal888 [$50](https://agilebits.com/store)

**Comment by stal888** [comment]
@stqism thats bloody expensive m8

you could buy a whole half an anime figure with that kind of dosh

**Comment by TheLastProject** [comment]
A bug icon is not clear at all. I still fail to see what's wrong with this pull request, as it's simple and unobnoxious:
warning

It's also not about bugs, it's also about possible security risks, because we haven't had an audit yet.

**Comment by pwnsdx** [comment]
The website looks so ugly in your browser, what browser/os are you using?

**Comment by TheLastProject** [comment]
Firefox 36 on Gentoo. If it "looks so ugly" it's probably falling back to an unintended font, but that really seems off-topic now.

**Comment by pwnsdx** [comment]
Yes, just wanted to know. About the security risks, there is always security risks in beta or alpha softwares.

**Comment by TheLastProject** [comment]
Which is exactly why we should tell people this is alpha software. Currently, the new site does not do that at all.

**Comment by pwnsdx** [comment]
Before it was the case, the download button was "Download alpha", now it looks like it has been changed by "Download qTox". I don't know why.

**Comment by urras** [comment]
Does something along the lines of what inqlude.org is doing sound good?

**Comment by pwnsdx** [comment]
Yep it looks great, maybe "flatter" (like the download button)

Btw Nick, did you received my e-mail I sent some days ago ?

**Comment by urras** [comment]
I don't think I did, sorry.

**Pull request closed without merging**
